modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "chattranslate"
version = "${version}"
displayName = "ChatTranslate"
authors = "PlumeIS"
description = '''
ChatTranslate
'''
#logoFile = ""

[[dependencies.chattranslate]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chattranslate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"