modLoader = "javafml"
loaderVersion = "[39,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "translateoverlay"
version = "${version}"
displayName = "TranslateOverlay"
authors = "PlumeIS"
description = '''
TranslateOverlay
'''
logoFile = "icon.png"

[[dependencies.translateoverlay]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.translateoverlay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"