modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "translateoverlay"
version = "${version}"
displayName = "TranslateOverlay"
authors = "PlumeIS"
description = '''
TranslateOverlay
'''
#logoFile = ""

[[dependencies.translateoverlay]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.translateoverlay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"